.MODEL SMALL
.STACK 100H
.DATA
	NUM DB 7
	MSGGREATER DB 'Greater'
	MSGNOTGREATER DB 'Not Greater$'
.CODE
MAIN PROC
	MOV AX,@DATA
	MOV DS,AX
	
	MOV AL,NUM ; AL = 7
	CMP AL,5 ; COMPARE THE VALUE OF AL AND 5 
	JA GREATERLABEL ; JUMP ABOVE IF AL IS ABOVE 5 THEN JUMP TO ...
	
	LEA DX,MSGNOTGREATER
	MOV AH,09H
	INT 21H
	JMP END_PGM ; UNCONDITIONAL JUMP
GREATERLABEL:
	LEA DX,MSGGREATER
	MOV AH,09H
	INT 21H
END_PGM:	
	MOV AH,4CH
	INT 21H

MAIN ENDP
END MAIN