.MODEN SMALL
.STACK 100H

.CODE
MAIN PROC
	MOV AX,0 ; AX = 0 
	MOV AX,0 ; COMPARE THE VALUE OF AX WITH 0 
	JE END_IF ; JUMP EQUAL IF AX VAULE IS EQUAL TO 0 THEN JUMP TP END_IF 
	ADD AX,1
END_IF:
	MOV DX,AX
	ADD DX,'0'
	MOV AH,02H
	INT 21H
	
	
	MOV AH,4CH
	INT 21H
MAIN ENDP
END MAIN