.MODEL SMALL
.STACK 100H
.DATA
	NL DB 0DH, OAH, '$'
.CODE
MAIN PROC
	MOV AX,@DATA
	MOV DS,AX

	MOV CL,1 ; CL = 1
WHILE_START:
	CMP CL,9 ; 8 AND 9 
	JGE WHILE_END ; JUMP GREATER THAN OR EQUAL TO IF CL>9 THEN JUMP ...
	
	; DISPLAY VALUE OF CL ON THE SCREEN	
	MOV DL,CL,
	ADD DL,'0'
	MOV AH,02H
	INT 21H

	INC CL ; 8
	
	JMP WHILE_STAFF
WHILE_END:

	MOV AH,4CH
	INT 21H
MAIN ENDP
END MAN	